export const linkData = [
    {
        id:1,
        path:'/',
        text:'home'
    },
    {
        id:2,
        path:'/about',
        text:'about'
    },
    {
        id:3,
        path:'/products',
        text:'product'
    },
    {
        id:4,
        path:'/contact',
        text:'contact'
    },
    {
        id:5,
        path:'/cart',
        text:'cart'
    }
];